# Generated by Django 5.2.3 on 2025-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatlisting',
            name='category',
            field=models.CharField(choices=[('', 'Избери...'), ('Платноходка', 'Платноходка'), ('Моторна лодка', 'Моторна лодка'), ('Яхта', 'Яхта'), ('Рибарска лодка', 'Рибарска лодка'), ('Надуваема лодка', 'Надуваема лодка'), ('Скутер', 'Скутер'), ('Други', 'Други')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='boatlisting',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('', 'Избери...'), ('Бензинова', 'Бензинова'), ('Дизелова', 'Дизелова'), ('Бензинова/Газ', 'Бензинова/Газ'), ('Хибридна', 'Хибридна'), ('Електрическа', 'Електрическа')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motolisting',
            name='category',
            field=models.CharField(choices=[('', 'Избери...'), ('Спортен', 'Спортен'), ('Нейкед', 'Нейкед'), ('Туристически', 'Туристически'), ('Круизър', 'Круизър'), ('Скутер', 'Скутер'), ('Ендуро', 'Ендуро'), ('Крос', 'Крос'), ('ATV / Бъги', 'ATV / Бъги'), ('Други', 'Други')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motolisting',
            name='engine_type',
            field=models.CharField(choices=[('', 'Избери...'), ('2-stroke', '2 тактов'), ('4-stroke', '4 тактов'), ('electric', 'Електрически')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motolisting',
            name='fuel_type',
            field=models.CharField(choices=[('', 'Избери...'), ('Бензинова', 'Бензинова'), ('Дизелова', 'Дизелова'), ('Бензинова/Газ', 'Бензинова/Газ'), ('Хибридна', 'Хибридна'), ('Електрическа', 'Електрическа')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motolisting',
            name='kilometers',
            field=models.PositiveIntegerField(default=15000, help_text='в километри'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motolisting',
            name='transmission',
            field=models.CharField(choices=[('', 'Избери...'), ('manual', 'Ръчна'), ('automatic', 'Автоматична')], max_length=20),
        ),
    ]
